Bug fix: Different index type caused problems when filtering. Cast as list in stead.
pandas.core.indexing.IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match)