Initial support for Azure Data Lake Gen2 (#1039)
* FileSystem abstraction first commit

* Fixing ADLGen1FileSystem.create_from_env()

* file_system/adl1.py unit test

* test_open() for ADLGen1FileSystem

* test_isfile() and test_isdir() for ADLGen1FileSystem

* test_info_directory(), test_info_file() for ADLGen1FileSystem

* test_walk()

* First attempt to move whole codebase to ADLGen1FileSystem

* Black reformating

* Fix FileSystem.join()

* Fixing all unit tests

* Fix pyflake errors

* Fixing pyflakes issues

* Fix typing

* Fix documentation

* Fix one type casting

* Additinal argument dl_service_auth_env for ADLGen1FileSystem.create_from_env()

* Fix error: missing 1 required positional argument: 'fs'

* FileSystem.name

* azure-storage-file-datalake~=12.1.2

* ADLGen2FileSystem first attempt

* black reformating

* Rename test adl1.py -> test_adl1.py

* Work on new DiffBasedAnomalyDetector with different CV methodology + shuffling (#1025)

* Add imports change name of imported cross_validate

* Change scaled mse function

* Add absolute error method

* Change default scaler

* Change window typing

* Add DiffBasedFFAnomalyDetector class

* Add get_params method

* Add fit method

* Add threshold methods

* Add cross_validate method

* Add get_metadata method

* Revert scaled_mse and other fixes

* Add random_state to ensure consistency

* Update deprecated imports

* Fix tests

* Add serialization test

* Revert change

* Add require_thresholds as param

* Change calculation of threshold to pandas method

* Adapt tests for DiffBasedKFCVAnomalyDetector

* Add get_metadata test

* Add support for choosing smoothing_method

* Adapt tests to new smoothing_method arg

* Fix docstring

* Move cv parameter definition to function arg

* Add shuffle arg to base class & change .fit

* Adapt doctrings

* Change percentile default

* Add shuffle to metadata

* Adapt tests to latest changes

* Change name of X, y inside `fit`

* Remove `self` from function argument.

* Move setter for `smoothing_method` in case
`window` is not `None` to __init__()`

* unit tests for ADLGen2FileSystem

* Black reformating

* First version of AssetToPathConfig

* asset_to_path.py -> assets_config.py

* Speed up filtering (#1040)

* update filtering

* removed old function

* paramtere naming update

* added defaults

* added `known_filter_periods`
removed redundant error-class

* updated error class

* removed error class

* black

* added config element

* Optional parameter

* removed unused import

* new max mask evaluations

* added tests

* set default optional values
logical fix

* assert to raise

* evaluate filter string and filter list separately

* added ConfigurationError

* black

* typo

* marshmallow==3.3.0

* AssetsConfig() almost finished

* Unit tests for AssetsConfig()

* Additinal docstrings

* Changes scaler from RobusScaler to MinMaxScaler (#1041)

* Refactoring for DataLakeProvider. Not finished

* Fix docstring

* Fixing all unittests

* Delete debug prints

* Black reformating

* resource_assets_config

* Additional hardcode for DataLake

* Fix one mypy error

* Fix rest of mypy errors

* Still have some unresolved unittests

* Fix test_config_elemets unittest

* Black reformating

* Fix unittest test_data_provider_iroc

* Fixing tests test_data_provider_iroc and test_ncs_reader

* All unittests should be fixed

* Fixing unused imports

* Upgrade walk() and ls() for ADL1FileSystem

* Adding create_time for FileInfo, start refactoring ADL2FileSystem

* Finishing with test_adl2

* NcsLookup first version

* test_ncs_file_type

* MockFileSystem

* Revert "MockFileSystem"

This reverts commit 828f0bc32510ba5b0cb1acbcf68168d8a6ba4f13.

* Do NcsLookup in more simpler way

* Moving from unittest to pytest on test_data_provider_iroc

* Geting rid of MockFileSystem

* test_ncs_lookup

* Roll back anomaly confidence calculation (#1043)

* Roll back calculation of anomaly confidence
to use unsmoothed anomaly scores

* Remove commented code

* Fixing bug with race condition for GordoBaseDataset._metadata from multiple threads (#1045)

* Fix state of race condition for GordoBaseDataset._metadata

* Black reformating

* Forgot about super().__init__() for TimeSeriesDataset

* Dropping 'smooth_' columns from anomaly detection response in gordo-server (#1044)

* Fixing unittests in order to have ability to test that smooth_ columns are dropped

* Get rid of all smooth_ columns

* Fixing bug with race condition for GordoBaseDataset._metadata from multiple threads (#1045)

* Fix state of race condition for GordoBaseDataset._metadata

* Black reformating

* Forgot about super().__init__() for TimeSeriesDataset

* Fixing unittests in order to have ability to test that smooth_ columns are dropped

* Get rid of all smooth_ columns

* Fixing failed unittests leftovers

* Finishing coding parto for NcsLookup

* Remove years argument from one function in NcsLookup

* Exceptions for NcsLookup

* test_assets_config_tags_lookup

* Deleted debug prints

* Fix assets_config_tags_lookup in order to get all tags locations

* test_assets_config_tags_lookup_exceptions

* test_lookup_default

* test_lookup_default for multithreading

* test_lookup_exceptions

* mypy issues fixes

* Black reformating

* Fixing an issue with infinite retry loop in ForwardPredictionsIntoInflux (#1046)

* UnitTest for ForwardPredictionsIntoInflux._write_to_influx_with_retries() (#1048)

* Fixing problem with TimeSeriesDataset.row_filter_buffer_size larger than prediction dataframe size (#1047)

* Fixing problem with TimeSeriesDataset.row_filter_buffer_size larger than prediction dataframe size

* Fixing an issue with infinite retry loop in ForwardPredictionsIntoInflux (#1046)

* Fixing problem with TimeSeriesDataset.row_filter_buffer_size larger than prediction dataframe size

* Refactoring for NcsLookup

* Refactoring of NcsReader

* Fixing some tests

* Unit tests for TagLocations.years()

* ncs_storage module

* ncs_storage.py -> storages.py

* Add dls@omniadlseun for resource assets_config.yaml

* Update Gordo to allow trigger tag to be excluded from the input tags (#1049)

* First try for improvement trigger tags functionality

* Triggered tags for TimeSeriesDataset

* Parse triggered tags in right way

* Updating unit tests

* Fix test_dataset. TimeSeriesDataset.tag_noralizer

* Black reformating

* Fixing test_parse_filter_vars

* Docstring for parse_pandas_filter_vars

* Some additional docstrings

* Some additional docstrings

* test_parse_filter_vars testing for mailformed tag name

* parse_pandas_filter_vars with_special_vars argument

* Reformating test_parse_filter_vars

* Fixing test_config_elements unittest

* Black reformating

* Using dataset asset and default_asset for normalizing trigger tags (#1050)

* Using dataset asset and default_asset for normalizing trigger tags

* Black reformating

* Fixing doctest

* Fixing doctest

* Droping triggered tags columns before filtering periods (#1051)

* Adjustment of gordo-client dataset parameters (#1052)

* Adjusting gordo-client dataset parameters

* Droping triggered tags columns before filtering periods (#1051)

* Adjusting gordo-client dataset parameters

* add gordo model-build tolerations for azure spot instances. (#1053)

* Fix python identifiers escaping for triggered tags (#1054)

* Fix python identifiers escaping for triggered tags

* Black reformating

* Fixing pool size max error. Not tested yet

* Fixing issue with max HTTP connection pool size

* Unit tests leftovers

* store -> storage for NcsLookup

* Fix mypy error

* Fix Unit test

* Additinal Unit tests

* Black reformating

* Fix unused import warinig

* Delete debug print

* DEFAULT_STORAGE_TYPE = "adl1"

* Found type of GordoBaseDataProvider in right way

* Default storage={}

* Fix ValueError: Environment variable DL_SERVICE_AUTH_STR is empty

* Black reformating

* FileSystem abstraction first commit

* Fixing ADLGen1FileSystem.create_from_env()

* file_system/adl1.py unit test

* test_open() for ADLGen1FileSystem

* test_isfile() and test_isdir() for ADLGen1FileSystem

* test_info_directory(), test_info_file() for ADLGen1FileSystem

* test_walk()

* First attempt to move whole codebase to ADLGen1FileSystem

* Black reformating

* Fix FileSystem.join()

* Fixing all unit tests

* Fix pyflake errors

* Fixing pyflakes issues

* Fix typing

* Fix documentation

* Fix one type casting

* Additinal argument dl_service_auth_env for ADLGen1FileSystem.create_from_env()

* Fix error: missing 1 required positional argument: 'fs'

* FileSystem.name

* azure-storage-file-datalake~=12.1.2

* ADLGen2FileSystem first attempt

* black reformating

* Rename test adl1.py -> test_adl1.py

* unit tests for ADLGen2FileSystem

* Black reformating

* First version of AssetToPathConfig

* asset_to_path.py -> assets_config.py

* marshmallow==3.3.0

* AssetsConfig() almost finished

* Unit tests for AssetsConfig()

* Additinal docstrings

* Refactoring for DataLakeProvider. Not finished

* Fix docstring

* Fixing all unittests

* Delete debug prints

* Black reformating

* resource_assets_config

* Additional hardcode for DataLake

* Fix one mypy error

* Fix rest of mypy errors

* Still have some unresolved unittests

* Fix test_config_elemets unittest

* Black reformating

* Fix unittest test_data_provider_iroc

* Fixing tests test_data_provider_iroc and test_ncs_reader

* All unittests should be fixed

* Fixing unused imports

* Upgrade walk() and ls() for ADL1FileSystem

* Adding create_time for FileInfo, start refactoring ADL2FileSystem

* Finishing with test_adl2

* NcsLookup first version

* test_ncs_file_type

* MockFileSystem

* Revert "MockFileSystem"

This reverts commit 828f0bc32510ba5b0cb1acbcf68168d8a6ba4f13.

* Do NcsLookup in more simpler way

* Moving from unittest to pytest on test_data_provider_iroc

* Geting rid of MockFileSystem

* test_ncs_lookup

* Finishing coding parto for NcsLookup

* Remove years argument from one function in NcsLookup

* Exceptions for NcsLookup

* test_assets_config_tags_lookup

* Deleted debug prints

* Fix assets_config_tags_lookup in order to get all tags locations

* test_assets_config_tags_lookup_exceptions

* test_lookup_default

* test_lookup_default for multithreading

* test_lookup_exceptions

* mypy issues fixes

* Black reformating

* Refactoring for NcsLookup

* Refactoring of NcsReader

* Fixing some tests

* Unit tests for TagLocations.years()

* ncs_storage module

* ncs_storage.py -> storages.py

* Add dls@omniadlseun for resource assets_config.yaml

* Fixing pool size max error. Not tested yet

* Fixing issue with max HTTP connection pool size

* Unit tests leftovers

* store -> storage for NcsLookup

* Fix mypy error

* Fix Unit test

* Additinal Unit tests

* Black reformating

* Fix unused import warinig

* Delete debug print

* DEFAULT_STORAGE_TYPE = "adl1"

* Found type of GordoBaseDataProvider in right way

* Default storage={}

* Fix ValueError: Environment variable DL_SERVICE_AUTH_STR is empty

* Black reformating

* ExceptionReporter for ConfigError

* Fix unit test

* Fix mypy errors

* Some fixes in DataLakeProvider

* Additional docstrings

* Black reformating

* Fix unit test

* Additional docstring

* Fix CVE issue for docker containers

Co-authored-by: Hugo Bettencourt Machado <hbett@equinor.com>
Co-authored-by: Henrik Nyhus <henriknyhus@gmail.com>
Co-authored-by: Haithem Jarraya <hjarraya@users.noreply.github.com>